version: '3'

services:
  edge:
    build:
      context: ./edge
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    environment:
      - API_MANAGER_HOST=api-manager

  api-manager:
    build:
      context: ./api-manager
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "80:80"
    environment:
      - DB_HOST=postgres
      - DB_USER=dev
      - DB_PASSWORD=1123
      - DB_NAME=lemon

  postgres:
    image: postgres:12.0-alpine
    ports:
      - "5433:5432"
    volumes:
      - postgresdb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 1123
      POSTGRES_DB: lemon
    restart: unless-stopped

volumes:
  postgresdb:
